/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_MessageFrame;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module MsgFrame in /home/chengtao/Documents/github/v2x/ADS/v2x_asn/MsgFrame.asn */
	&asn_DEF_MessageFrame,	
	0
};

